server:
  port: 8087

spring:
  application:
    name: notification-service
  config:
    import: "optional:configserver:http://config-server:8888,optional:common.yml"
rabbitmq:
  host: localhost # or rabbitmq (if running via Docker Compose)
  port: 5672
  username: guest
  password: guest

  order:
    queue: order.queue
    exchange: order.exchange
    routing-key: order.created.key

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

logging:
  level:
    org.springframework: INFO
