server:
  port: 8082

spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://config-server:8888
  rabbitmq:
    host: localhost  # or rabbitmq (if running via Docker Compose)
    port: 5672
    username: guest
    password: guest
    queue: order.queue
  datasource:
    url: jdbc:postgresql://order-db:5432/orderdb
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
